version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: sysinfo
    versions:
    - 0.16.0
  - dependency-name: mockito
    versions:
    - 0.29.0
